---
title: "DeIdentify Data"
output: html_notebook
---

```{r}
# Read the data
data2 <- readxl::read_xls("Lectures/Class_4/nbr_hoch_ps2.xls")

set.seed(1)
d <- Boot_sample(data2, 1)[[1]]
d <- d %>%
  mutate(effect = scales::rescale(x = effect, to = c(rnorm(1, mean = min(d$effect), sd = sd(effect))*3,
                                                     rnorm(1, mean = max(d$effect), sd = sd(effect))*3)),
         cost = scales::rescale(cost, to = c(rnorm(1, min(cost), sd = sd(cost))/4,
                                             rnorm(1, max(cost), sd(cost))/4))) 


range(data2$effect)
range(data2$cost)

range(d$effect)
range(d$cost)

save(d, file = "data/CEA2.rda")
readr::write_rds(x = d, path = "data/CEA2.rds")
```

```{r}
round(ICER(d), 2)

### Get the INB
lambdas <- c(0, 500, 1e3, 5e3, 10e3)
plotINB(data = d, lambdas)
#### Uncertainty ####
# Fieller's CI (a.k.a Parametric)
CIf <- Fiellers_CI(d)
# Ellipse CI
Elipse_CI(data = d, confidence = 0.95, plot = T)

# INB
CEAC(data = d, N_Sim = 1000, NB = lambdas)
```

```{r}

```

